AWSTemplateFormatVersion: '2010-09-09'
Description: General S3 bucket for Zero to Sam Hero code.
  This can be ignored if you have another bucket you want
  to use instead

Resources:
  ZtshArtifactStoreS3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  ZtshArtifactStoreS3ArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${AWS::StackName}-source-bucket
      Description: Bucket for ZtSH source code
      Type: String
      Value: !Ref ZtshArtifactStoreS3
