AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  NodeLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: A starter AWS Lambda function.
      Runtime: nodejs6.10
      Handler: app.handler

  NodeLambdaArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: node-lambda-arn
      Description: ARN for node lambda example
      Type: String
      Value: !GetAtt NodeLambda.Arn
