AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  PythonLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: A starter AWS Lambda function.
      Runtime: python2.7
      Handler: handler.main
      CodeUri: ./dist
      Environment:
        Variables:
          S3_BUCKET: !Sub ${AWS::StackName}-${AWS::Region}-${AWS::AccountId}
      Policies:
       - AWSLambdaExecute
       - Version: '2012-10-17'
         Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource:
              - !Sub arn:aws:s3:::${AWS::StackName}-${AWS::Region}-${AWS::AccountId}/* # This is gross but prevents circulars

  PythonLambdaArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: python-lambda-arn
      Description: ARN for python lambda example
      Type: String
      Value: !GetAtt PythonLambda.Arn

  PythonLambdaReadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::Region}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

